export const characters = [
  "akuma",
  "alisa",
  "anna",
  // 'armor king',
  // 'asuka',
  // 'bob',
  // 'bryan',
  // 'claudio',
  // 'devil jin',
  // 'dragunov',
  // 'eddy',
  // 'eliza',
  // 'fahkumram',
  // 'feng',
  // 'ganryu',
  // 'geese',
  // 'gigas',
  // 'heihachi',
  // 'hwoarang',
  // 'jack',
  // 'jin',
  // 'josie',
  // 'julia',
  // 'katarina',
  // 'kazumi',
  // 'kazuya',
  // 'king',
  // 'kuma',
  // 'lars',
  // 'law',
  // 'lee',
  // 'lei',
  // 'leo',
  // 'leroy',
  // 'lili',
  // 'lucky chloe',
  // 'marduk',
  // 'master raven',
  // 'miguel',
  // 'negan',
  // 'nina',
  // 'noctis',
  // 'paul',
  // 'shaheen',
  // 'steve',
  // 'xiaoyu',
  // 'yoshimitsu',
  // 'zafina',
];
