export let gigas = [
  {
    Command: "in rage 1+2",
    "Hit level": "m (TJ)",
    Damage: "55",
    "Start up frame": "20~21 pc8~17 js8~17",
    "Block frame": "-42~-41",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "Rage art",
  },
  {
    Command: "in rage f+3+4*",
    "Hit level": "! (GOL)",
    Damage: "0",
    "Start up frame": "29",
    "Block frame": "+81",
    "Hit frame": "+81",
    "Counter hit frame": "+81",
    Notes: "Rage drive",
  },
  {
    Command: "1",
    "Hit level": "h",
    Damage: "7",
    "Start up frame": "10",
    "Block frame": "+1",
    "Hit frame": "+8",
    "Counter hit frame": "+8",
    Notes: "",
  },
  {
    Command: "1, 2",
    "Hit level": "h, h",
    Damage: "7,24",
    "Start up frame": "10",
    "Block frame": "-17",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "2",
    "Hit level": "h",
    Damage: "10",
    "Start up frame": "10",
    "Block frame": "-5",
    "Hit frame": "+6",
    "Counter hit frame": "+6",
    Notes: "",
  },
  {
    Command: "2, 1",
    "Hit level": "h, h",
    Damage: "10,12",
    "Start up frame": "10",
    "Block frame": "-6",
    "Hit frame": "+5",
    "Counter hit frame": "+5",
    Notes: "",
  },
  {
    Command: "2, 1, 3+4",
    "Hit level": "h, h, (SG)",
    Damage: "10,12",
    "Start up frame": "10",
    "Block frame": "-4",
    "Hit frame": "+7",
    "Counter hit frame": "+7",
    Notes: "",
  },
  {
    Command: "3",
    "Hit level": "m",
    Damage: "17",
    "Start up frame": "14~15",
    "Block frame": "-9~-8",
    "Hit frame": "+2~+3",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "4",
    "Hit level": "m",
    Damage: "20",
    "Start up frame": "16~17",
    "Block frame": "-9~-8",
    "Hit frame": "+2~+3",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+2",
    "Hit level": "h",
    Damage: "20",
    "Start up frame": "16~18",
    "Block frame": "-9~-7",
    "Hit frame": "+7~+9",
    "Counter hit frame": "CS",
    Notes: "",
  },
  {
    Command: "f+2, 1",
    "Hit level": "h, h",
    Damage: "20,17",
    "Start up frame": "16~18",
    "Block frame": "-3~-2",
    "Hit frame": "+5~+6",
    "Counter hit frame": "+5~+6",
    Notes: "",
  },
  {
    Command: "f+2, 1, 1",
    "Hit level": "h, h, m",
    Damage: "20,17,25",
    "Start up frame": "16~18",
    "Block frame": "-12~-11",
    "Hit frame": "KMUD",
    "Counter hit frame": "KMUD",
    Notes: "",
  },
  {
    Command: "f+2, f+1",
    "Hit level": "h, h",
    Damage: "20,20",
    "Start up frame": "16~18",
    "Block frame": "-9~-8",
    "Hit frame": "CS",
    "Counter hit frame": "CS",
    Notes: "Tail spin",
  },
  {
    Command: "f+2, d+1",
    "Hit level": "h, m",
    Damage: "20,17",
    "Start up frame": "16~18",
    "Block frame": "-13~-12s",
    "Hit frame": "+2~+3s",
    "Counter hit frame": "+2~+3s",
    Notes: "",
  },
  {
    Command: "f+2, d+1, 3+4",
    "Hit level": "h, m, (SG)",
    Damage: "20,17",
    "Start up frame": "16~18",
    "Block frame": "-2s",
    "Hit frame": "+13s",
    "Counter hit frame": "+13s",
    Notes: "",
  },
  {
    Command: "f+3",
    "Hit level": "m",
    Damage: "17",
    "Start up frame": "23",
    "Block frame": "-9",
    "Hit frame": "+9",
    "Counter hit frame": "+9",
    Notes: "",
  },
  {
    Command: "f+3, 2",
    "Hit level": "m, m",
    Damage: "17,20",
    "Start up frame": "23~24",
    "Block frame": "-13",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+3, 2, F",
    "Hit level": "m, m, (GOL)",
    Damage: "17,20",
    "Start up frame": "23~24",
    "Block frame": "-27",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+3, 2*",
    "Hit level": "m, m",
    Damage: "17,40",
    "Start up frame": "23~24",
    "Block frame": "+15g",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+3, 2*, F",
    "Hit level": "m, m, (GOL)",
    Damage: "17,40",
    "Start up frame": "23~24",
    "Block frame": "+18",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+4",
    "Hit level": "m",
    Damage: "20",
    "Start up frame": "24",
    "Block frame": "-14",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+4, F",
    "Hit level": "m, (GOL)",
    Damage: "20",
    "Start up frame": "24",
    "Block frame": "-18",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+4*",
    "Hit level": "m",
    Damage: "40",
    "Start up frame": "43~44",
    "Block frame": "+26g",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+4*, F",
    "Hit level": "m, (GOL)",
    Damage: "40",
    "Start up frame": "43~44",
    "Block frame": "+18",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "f+1+2",
    "Hit level": "h",
    Damage: "20",
    "Start up frame": "13",
    "Block frame": "-9",
    "Hit frame": "+6s",
    "Counter hit frame": "Throw",
    Notes: "",
  },
  {
    Command: "f+1+2(CH in front)",
    "Hit level": "h, (throw)",
    Damage: "18,10*4",
    "Start up frame": "13",
    "Block frame": "",
    "Hit frame": "",
    "Counter hit frame": "Throw",
    Notes: "",
  },
  {
    Command: "d/f+1",
    "Hit level": "m",
    Damage: "14",
    "Start up frame": "14",
    "Block frame": "-6",
    "Hit frame": "+4",
    "Counter hit frame": "+4",
    Notes: "",
  },
  {
    Command: "d/f+2",
    "Hit level": "m",
    Damage: "15",
    "Start up frame": "15",
    "Block frame": "-7",
    "Hit frame": "+6",
    "Counter hit frame": "+6",
    Notes: "",
  },
  {
    Command: "d/f+2, 1",
    "Hit level": "m, m",
    Damage: "14,21",
    "Start up frame": "15",
    "Block frame": "-13~-12",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "Tail spin",
  },
  {
    Command: "d/f+3",
    "Hit level": "m",
    Damage: "11",
    "Start up frame": "13",
    "Block frame": "-9",
    "Hit frame": "+4",
    "Counter hit frame": "+4",
    Notes: "",
  },
  {
    Command: "d/f+3, 1",
    "Hit level": "m, h",
    Damage: "11,12",
    "Start up frame": "13",
    "Block frame": "-4",
    "Hit frame": "+4",
    "Counter hit frame": "+10",
    Notes: "",
  },
  {
    Command: "d/f+3, 1+2",
    "Hit level": "m, m",
    Damage: "11,20",
    "Start up frame": "13",
    "Block frame": "-16",
    "Hit frame": "CS",
    "Counter hit frame": "CS",
    Notes: "",
  },
  {
    Command: "d/f+3, 1+2, 1+2",
    "Hit level": "m, m, h",
    Damage: "11,20,20",
    "Start up frame": "13",
    "Block frame": "-1~0",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "d/f+4",
    "Hit level": "m",
    Damage: "12",
    "Start up frame": "14",
    "Block frame": "-3",
    "Hit frame": "+3",
    "Counter hit frame": "+9",
    Notes: "",
  },
  {
    Command: "d/f+4, 1+2",
    "Hit level": "m, m",
    Damage: "12,30",
    "Start up frame": "14",
    "Block frame": "+1~+2s",
    "Hit frame": "+5~+6s",
    "Counter hit frame": "+5~+6s",
    Notes: "",
  },
  {
    Command: "d/f+1+2",
    "Hit level": "mm",
    Damage: "13,13",
    "Start up frame": "25~26, 47~48",
    "Block frame": "-20~-19",
    "Hit frame": "-9~-8s",
    "Counter hit frame": "KND(KND)",
    Notes: "",
  },
  {
    Command: "d/f+1+2, 1+2",
    "Hit level": "mm, m",
    Damage: "13,13,20",
    "Start up frame": "25~26, 47~48",
    "Block frame": "-18~-17s",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "d+2",
    "Hit level": "m",
    Damage: "13",
    "Start up frame": "15",
    "Block frame": "-14",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "d+3",
    "Hit level": "l",
    Damage: "15",
    "Start up frame": "16",
    "Block frame": "-12",
    "Hit frame": "-1",
    "Counter hit frame": "-1",
    Notes: "",
  },
  {
    Command: "d+3, 2",
    "Hit level": "l, m",
    Damage: "15,20",
    "Start up frame": "16",
    "Block frame": "-12s",
    "Hit frame": "0s",
    "Counter hit frame": "KND",
    Notes: "",
  },
  {
    Command: "d+1+2",
    "Hit level": "m",
    Damage: "30",
    "Start up frame": "30~31 pc8~29",
    "Block frame": "-13~-12",
    "Hit frame": "KND",
    "Counter hit frame": "KND",
    Notes: "Wall bounce, Power crush",
  },
  {
    Command: "d+3+4",
    "Hit level": "(Special)",
    Damage: "",
    "Start up frame": "pc6~",
    "Block frame": "",
    "Hit frame": "",
    "Counter hit frame": "",
    Notes: "Power crush",
  },
  {
    Command: "d/b+2",
    "Hit level": "l (TC)",
    Damage: "20",
    "Start up frame": "23~24 cs6~",
    "Block frame": "-14~-13",
    "Hit frame": "+3~+4",
    "Counter hit frame": "KND",
    Notes: "",
  },
];
